export default {
  HOME: 'Inicio',
  BATTLES: 'Conciertos',
  BATTLE: 'Concierto',
  PLAY_BATTLE: 'Dar concierto',
  INVESTMENTS: 'Inversiones',
  BUY_INVESTMENT_ITEM: 'Invertir',
  SHOP: 'Tienda',
  BUY_SHOP_ITEM: 'Item de Tienda',
  BANK: 'Bancos',
  MANAGER_TIP: 'Manager',
  SIGN_UP: 'Creá tu rapero',
  SIGN_IN: 'Ingresá a la experiencia',
  APP: 'App',
  AUTH: 'Auth',
}
