export default {
  HOME: 'Inicio',
  BANK: 'Banco',
  RANKING: 'Ranking',
  FANS: 'Fans',
  FLOW: 'Flow',
  MONEY: 'Dinero',
  INCREASE_CREDIT_CARD_LIMIT: 'Incrementar límite de tarjeta de crédito',
  PAY_CREDIT_CARD: 'Pagar tarjeta de crédito',
  PAY_LOAN: 'Pagar préstamo',
  REQUEST_LOAN: 'Pedir préstamo',
  REQUEST_FIXED_TERM_DEPOSIT: 'Pedir plazo fijo',
  BATTLES: 'Conciertos',
  BATTLE: 'Concierto',
  PLAY_BATTLE: 'Dar concierto',
  INVESTMENTS: 'Inversiones',
  BUY_INVESTMENT_ITEM: 'Invertir',
  SHOP: 'Tienda',
  BUY_SHOP_ITEM: 'Item de Tienda',
  MANAGERS: 'Manager',
  MANAGER_TIP: 'Tip del Manager',
  SIGN_UP: 'Creá tu rapero',
  SIGN_IN: 'Ingresá a la experiencia',
  APP: 'App',
  AUTH: 'Auth',
}
